{{- if .Values.smtp.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.smtp.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "podmonitor-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.smtp.password | quote }}
{{- end }}

