apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: podmonitor-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: podmonitor-manager-role
subjects:
- kind: ServiceAccount
  name: podmonitor-controller-manager
  namespace: podmonitor-system

