apiVersion: v1
entries:
  podmonitor-operator:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-01-06T17:50:35.5481325+08:00"
    description: A Kubernetes Operator for monitoring and cleaning up zombie pods
    digest: 7589e28568f6fd26834cff4c96ff6a551d3b73246200dc8a61ae0e92b3d1225a
    home: https://github.com/pod-monitor/operator
    keywords:
    - kubernetes
    - operator
    - pod-monitor
    - zombie-pods
    - monitoring
    maintainers:
    - name: PodMonitor Team
    name: podmonitor-operator
    sources:
    - https://github.com/pod-monitor/operator
    type: application
    urls:
    - podmonitor-operator-0.1.0.tgz
    version: 0.1.0
generated: "2026-01-06T17:50:35.5461484+08:00"
