apiVersion: v1
entries:
  podmonitor-operator:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-01-06T17:17:00.7008521+08:00"
    description: A Kubernetes Operator for monitoring and cleaning up zombie pods
    digest: c13173471c1e82ac9f9fb9323eeb54109c465eba84c81d951ed4ea2bf1c0bc83
    home: https://github.com/pod-monitor/operator
    keywords:
    - kubernetes
    - operator
    - pod-monitor
    - zombie-pods
    - monitoring
    maintainers:
    - name: PodMonitor Team
    name: podmonitor-operator
    sources:
    - https://github.com/pod-monitor/operator
    type: application
    urls:
    - podmonitor-operator-0.1.0.tgz
    version: 0.1.0
generated: "2026-01-06T17:17:00.6996859+08:00"
