apiVersion: v1
entries:
  podmonitor-operator:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-01-07T14:38:36.7665017+08:00"
    description: A Kubernetes Operator for monitoring and cleaning up zombie pods
    digest: 9f82063ed441c93960354c5f73de3413b23a3be2f94fdab11960d49b7d4d0eb2
    home: https://github.com/pod-monitor/operator
    keywords:
    - kubernetes
    - operator
    - pod-monitor
    - zombie-pods
    - monitoring
    maintainers:
    - name: PodMonitor Team
    name: podmonitor-operator
    sources:
    - https://github.com/pod-monitor/operator
    type: application
    urls:
    - podmonitor-operator-0.1.0.tgz
    version: 0.1.0
generated: "2026-01-07T14:38:36.7653249+08:00"
