apiVersion: v1
entries:
  podmonitor-operator:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-01-06T17:57:41.2598767+08:00"
    description: A Kubernetes Operator for monitoring and cleaning up zombie pods
    digest: 094fa10c06201d5c1692ee058c74a9631b53c9dfe49bdbb27ec8b2c748dc3c8f
    home: https://github.com/pod-monitor/operator
    keywords:
    - kubernetes
    - operator
    - pod-monitor
    - zombie-pods
    - monitoring
    maintainers:
    - name: PodMonitor Team
    name: podmonitor-operator
    sources:
    - https://github.com/pod-monitor/operator
    type: application
    urls:
    - podmonitor-operator-0.1.0.tgz
    version: 0.1.0
generated: "2026-01-06T17:57:41.2587603+08:00"
