apiVersion: v1
entries:
  podmonitor-operator:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-01-05T17:55:27.305293+08:00"
    description: A Kubernetes Operator for monitoring and cleaning up zombie pods
    digest: 3e211ddcfbc1e4421a4a6f6407a0779bbed6b38347d12f09cd06dfc947ad75a5
    home: https://github.com/pod-monitor/operator
    keywords:
    - kubernetes
    - operator
    - pod-monitor
    - zombie-pods
    - monitoring
    maintainers:
    - name: PodMonitor Team
    name: podmonitor-operator
    sources:
    - https://github.com/pod-monitor/operator
    type: application
    urls:
    - podmonitor-operator-0.1.0.tgz
    version: 0.1.0
generated: "2026-01-05T17:55:27.304708+08:00"
